# config.py

# 게임 상수
WIDTH = 480
HEIGHT = 640
FPS = 60

# Pyxel 색상 팔레트 (RGB 대신 0-15 인덱스)
COLOR_BLACK = 0
COLOR_WHITE = 7
COLOR_RED = 8
COLOR_GREEN = 11 # HP UP 아이템 색상
COLOR_BLUE = 6
COLOR_YELLOW = 9 # OPTION 아이템 색상
COLOR_LIGHT_GREY = 13 # 적 총알 색상
COLOR_ORANGE = 10 # WING 아이템 색상
COLOR_PURPLE = 5
COLOR_CYAN = 12
COLOR_BOSS = 8
COLOR_ULTIMATE_GAUGE = 10 # 궁극기 게이지 색상 (주황색)
COLOR_BULLET_PLAYER_STRONG = 9 # 플레이어 총알 색상 (노란색)
COLOR_ITEM_OUTLINE = 7 # 아이템 외곽선 색상 (흰색)


# Player
PLAYER_SPEED = 3
PLAYER_BULLET_SPEED = 7
PLAYER_HP = 3 # 초기 플레이어 체력
PLAYER_MAX_HP = 5 # 최대 플레이어 체력 (아이템으로 증가 가능)

# Player Power-up
PLAYER_START_BULLET_W = 2
PLAYER_START_BULLET_H = 4
PLAYER_START_FIRE_RATE = 8 # 총알 발사 간격 (낮을수록 빠름)
PLAYER_MAX_POWER_LEVEL = 1 # 총알 강화 최대 레벨 (0:기본, 1:2줄, 2:3줄) - 최대 2번 업그레이드되도록 변경
PLAYER_OPTION_MAX = 2 # 옵션 최대 개수

# Enemy Bullet
ENEMY_BULLET_SPEED = 3
ENEMY_BULLET_WIDTH = 8  # 적 총알 너비
ENEMY_BULLET_HEIGHT = 8 # 적 총알 높이

# Enemy types
ENEMY_SIZE = 24 # 모든 적 기본 크기
ENEMY_TYPE_A_COLOR = COLOR_RED
ENEMY_TYPE_A_HP = 1
ENEMY_TYPE_A_SPEED = 1
ENEMY_TYPE_A_FIRE_RATE = 60 # A 타입 적 발사 간격 증가 (원래 90)
ENEMY_TYPE_A_WIDTH = ENEMY_SIZE
ENEMY_TYPE_A_HEIGHT = ENEMY_SIZE

ENEMY_TYPE_B_COLOR = COLOR_RED
ENEMY_TYPE_B_HP = 1
ENEMY_TYPE_B_SPEED = 0.8
ENEMY_TYPE_B_FIRE_RATE = 90 # B 타입 적 발사 간격 증가 (원래 120)
ENEMY_TYPE_B_WIDTH = ENEMY_SIZE
ENEMY_TYPE_B_HEIGHT = ENEMY_SIZE

ENEMY_TYPE_C_COLOR = COLOR_RED # Zigzag enemy
ENEMY_TYPE_C_HP = 1
ENEMY_TYPE_C_SPEED = 1.5
ENEMY_TYPE_C_ZIGZAG_AMPLITUDE = 20
ENEMY_TYPE_C_ZIGZAG_FREQUENCY = 15
ENEMY_TYPE_C_FIRE_RATE = 60 # C 타입 적 발사 간격 증가 (원래 90)
ENEMY_TYPE_C_WIDTH = ENEMY_SIZE
ENEMY_TYPE_C_HEIGHT = ENEMY_SIZE

ENEMY_TYPE_D_COLOR = COLOR_RED # Chasing enemy
ENEMY_TYPE_D_HP = 1
ENEMY_TYPE_D_SPEED = 0.5
ENEMY_TYPE_D_CHASE_THRESHOLD = 50
ENEMY_TYPE_D_WIDTH = ENEMY_SIZE
ENEMY_TYPE_D_HEIGHT = ENEMY_SIZE
ENEMY_TYPE_D_FIRE_RATE = 90 # D 타입 적 발사 간격 증가 (원래 120)

# Boss
BOSS_WIDTH = 120
BOSS_HEIGHT = 120
BOSS_HP = 300 # 보스 체력 유지
BOSS_COLOR = COLOR_BOSS

BOSS_PHASE1_HP_THRESHOLD = 200 # HP 역치 유지
BOSS_PHASE2_HP_THRESHOLD = 100 # HP 역치 유지

# Stages
STAGE1_ENEMY_COUNT = 10 # 적 개수 유지
STAGE1_BOSS_ACTIVE_TIME = 45 * FPS # 보스 등장 시간 증가 (원래 30 * FPS)
STAGE1_BACKGROUND_COLOR = COLOR_BLACK

STAGE2_ENEMY_COUNT = 15 # 적 개수 유지
STAGE2_BOSS_ACTIVE_TIME = 60 * FPS # 보스 등장 시간 증가 (원래 45 * FPS)
STAGE2_BACKGROUND_COLOR = COLOR_CYAN

ITEM_DROP_PROBABILITY = 0.5 # 일반 적 아이템 드랍 확률 유지
ITEM_BOSS_DROP_PROBABILITY = 1.0 # 보스 아이템 드랍 확률 유지
ITEM_SIZE = 24 # 아이템 크기 유지

# Ultimate
ULTIMATE_GAUGE_MAX = 100 # 궁극기 게이지 최대치 유지
ULTIMATE_GAUGE_PER_KILL = 10 # 적 한 마리당 얻는 게이지 유지
ULTIMATE_GAUGE_PER_BOSS_HIT = 3 # 보스에게 한 번 맞출 때 얻는 게이지 유지
ULTIMATE_EFFECT_DURATION = 15 # 궁극기 이펙트 지속 시간 유지